apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nestjs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:kozulova/argocd-demo.git"
    path: k8s
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
